package view;



import controller.IOFile;
import controller.TrongException;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CauThu;
import model.ViTri;

/**
 *
 * @author ADMIN
 */
public class Main extends javax.swing.JFrame {

    DefaultTableModel tmCT, tmVT;
    String fCT, fVT;
    List <CauThu> listCauThu;
    List <ViTri> listViTri;
    
    public Main() {
        initComponents();
        fCT = "src/controller/CT.dat";
        fVT = "src/controller/VT.dat";
        String [] ct = {"Ma cau thu", "Ho ten", "Tuoi", "Bang cap", "Luong"};
        String [] vt = {"Ma vi tri", "Ten vi tri", "He so thuong"};
        tmCT = new DefaultTableModel(ct, 0);
        tmVT = new DefaultTableModel(vt, 0);
        jTable1.setModel(tmCT);
        jTable2.setModel(tmVT);
        loadCT();
        loadVT();
        showCT(listCauThu);
        showVT(listViTri);
    }

    private void loadCT()
    {
        File f = new File(fCT);
        if(f.exists())
        {
            listCauThu = IOFile.doc(fCT);
        }
        else
        {
            listCauThu = new ArrayList<>();
        }
    }
    
    private void loadVT()
    {
        File f = new File(fVT);
        if(f.exists())
        {
            listViTri = IOFile.doc(fVT);
        }
        else
        {
            listViTri = new ArrayList<>();
        }
    }
    
    private void showCT(List <CauThu> lst)
    {
        tmCT.setRowCount(0);
        for(CauThu i : lst)
        {
            tmCT.addRow(i.toObject());
        }
    }
    
    private void showVT(List <ViTri> lst)
    {
        tmVT.setRowCount(0);
        for(ViTri i : lst)
        {
            tmVT.addRow(i.toObject());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelDichVu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaCT = new javax.swing.JTextField();
        txtTenCT = new javax.swing.JTextField();
        cbBangCap = new javax.swing.JComboBox<>();
        txtTuoi = new javax.swing.JTextField();
        txtLuong = new javax.swing.JTextField();
        btThemCT = new javax.swing.JButton();
        btSuaCT = new javax.swing.JButton();
        btLuuCT = new javax.swing.JButton();
        panelNhanVien = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaViTri = new javax.swing.JTextField();
        txtTenViTri = new javax.swing.JTextField();
        txtHeSoThuong = new javax.swing.JTextField();
        btThemViTri = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btLuuViTri = new javax.swing.JButton();
        panelQuanLy = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMaNV1 = new javax.swing.JTextField();
        txtHoTenNV1 = new javax.swing.JTextField();
        txtDiaChi1 = new javax.swing.JTextField();
        btThemNV1 = new javax.swing.JButton();
        btSuaNV1 = new javax.swing.JButton();
        btLuuNV1 = new javax.swing.JButton();
        btLamMoiNV1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ma cau thu:");

        jLabel2.setText("Ho ten:");

        jLabel3.setText("Tuoi");

        jLabel4.setText("Bang cap:");

        jLabel5.setText("Luong: ");

        txtMaCT.setEditable(false);
        txtMaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCTActionPerformed(evt);
            }
        });

        cbBangCap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "đại học", "cao đẳng ", "sơ cấp" }));

        txtTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTuoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(txtTenCT, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLuong))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txtTuoi))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cbBangCap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaCT)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbBangCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        btThemCT.setText("Them Cau Thu");
        btThemCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemCTActionPerformed(evt);
            }
        });

        btSuaCT.setText("Sua");
        btSuaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaCTActionPerformed(evt);
            }
        });

        btLuuCT.setText("Luu vao File");
        btLuuCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDichVuLayout = new javax.swing.GroupLayout(panelDichVu);
        panelDichVu.setLayout(panelDichVuLayout);
        panelDichVuLayout.setHorizontalGroup(
            panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDichVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDichVuLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDichVuLayout.createSequentialGroup()
                        .addComponent(btThemCT)
                        .addGap(37, 37, 37)
                        .addComponent(btSuaCT)
                        .addGap(47, 47, 47)
                        .addComponent(btLuuCT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDichVuLayout.setVerticalGroup(
            panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDichVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(33, 33, 33)
                .addGroup(panelDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemCT)
                    .addComponent(btSuaCT)
                    .addComponent(btLuuCT))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thong tin cau thu", panelDichVu);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setText("Ma vi tri: ");

        jLabel7.setText("Ten vi tri: ");

        jLabel9.setText("He so thuong: ");

        txtMaViTri.setEditable(false);
        txtMaViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaViTriActionPerformed(evt);
            }
        });

        txtHeSoThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeSoThuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(txtMaViTri))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenViTri, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(txtHeSoThuong))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTenViTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHeSoThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btThemViTri.setText("Them Vi Tri");
        btThemViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemViTriActionPerformed(evt);
            }
        });

        btXoa.setText("Xoa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btLuuViTri.setText("Luu vao File");
        btLuuViTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuViTriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNhanVienLayout = new javax.swing.GroupLayout(panelNhanVien);
        panelNhanVien.setLayout(panelNhanVienLayout);
        panelNhanVienLayout.setHorizontalGroup(
            panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNhanVienLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelNhanVienLayout.createSequentialGroup()
                        .addComponent(btThemViTri)
                        .addGap(37, 37, 37)
                        .addComponent(btXoa)
                        .addGap(47, 47, 47)
                        .addComponent(btLuuViTri)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelNhanVienLayout.setVerticalGroup(
            panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(33, 33, 33)
                .addGroup(panelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemViTri)
                    .addComponent(btXoa)
                    .addComponent(btLuuViTri))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thong tin vi tri ", panelNhanVien);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel11.setText("Cau thu: ");

        jLabel12.setText("Vi tri: ");

        jLabel13.setText("Ngay choi: ");

        txtMaNV1.setEditable(false);
        txtMaNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNV1ActionPerformed(evt);
            }
        });

        txtDiaChi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28)
                        .addComponent(txtMaNV1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHoTenNV1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(txtDiaChi1))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMaNV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtHoTenNV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtDiaChi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btThemNV1.setText("Them NV");
        btThemNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemNV1ActionPerformed(evt);
            }
        });

        btSuaNV1.setText("Sua");
        btSuaNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaNV1ActionPerformed(evt);
            }
        });

        btLuuNV1.setText("Luu vao File");
        btLuuNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuNV1ActionPerformed(evt);
            }
        });

        btLamMoiNV1.setText("Lam moi");
        btLamMoiNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLamMoiNV1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelQuanLyLayout = new javax.swing.GroupLayout(panelQuanLy);
        panelQuanLy.setLayout(panelQuanLyLayout);
        panelQuanLyLayout.setHorizontalGroup(
            panelQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQuanLyLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelQuanLyLayout.createSequentialGroup()
                        .addGroup(panelQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelQuanLyLayout.createSequentialGroup()
                                .addComponent(btThemNV1)
                                .addGap(37, 37, 37)
                                .addComponent(btSuaNV1)
                                .addGap(47, 47, 47)
                                .addComponent(btLuuNV1))
                            .addComponent(btLamMoiNV1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelQuanLyLayout.setVerticalGroup(
            panelQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuanLyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(33, 33, 33)
                .addGroup(panelQuanLyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemNV1)
                    .addComponent(btSuaNV1)
                    .addComponent(btLuuNV1))
                .addGap(18, 18, 18)
                .addComponent(btLamMoiNV1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bang phan cong", panelQuanLy);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSuaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaCTActionPerformed
        int r = jTable1.getSelectedRow();
        if(r >= 0 && r < jTable1.getRowCount())
        {
            String hoten = txtTenCT.getText();
            String ma = txtMaCT.getText();
            String tuoi = txtTuoi.getText();
            String bang = cbBangCap.getSelectedItem().toString();
            String luong = txtLuong.getText();
            
            tmCT.setValueAt(ma, r, 0);
            tmCT.setValueAt(hoten, r, 1);
            tmCT.setValueAt(tuoi, r, 2);
            tmCT.setValueAt(bang, r, 3);
            tmCT.setValueAt(luong, r, 4);
            int ma1 = Integer.parseInt(txtMaCT.getText());
            long luong1 = Long.parseLong(luong);
            int tuoi1 = Integer.parseInt(tuoi);
            CauThu temp = new CauThu(ma1, tuoi1, hoten, bang, luong1);
            listCauThu.set(r, temp);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Chon cau thu de sua! ");
            return;
        }
        
    }//GEN-LAST:event_btSuaCTActionPerformed

    private void txtMaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCTActionPerformed

    private void txtTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTuoiActionPerformed

    private void txtMaViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaViTriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaViTriActionPerformed

    private void txtHeSoThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeSoThuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeSoThuongActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        int r = jTable2.getSelectedRow();
        if(r >= 0 && r < jTable2.getRowCount())
        {
            tmVT.removeRow(r);
            listViTri.remove(r);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Chon vi tri de xoa! ");
            return;
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btThemCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemCTActionPerformed
        // TODO add your handling code here:
        int n = listCauThu.size();
        if(n > 0)
        {
            CauThu.setSma(listCauThu.get(n - 1).getMaCauThu()+ 1);
        }
        txtMaCT.setText(CauThu.getSma() + "");
        int maCauThu, tuoi;
        String hoTen, bangCap;
        long luong;
        try {
            hoTen = txtTenCT.getText();
            bangCap = cbBangCap.getSelectedItem().toString();
            tuoi = Integer.parseInt(txtTuoi.getText());
            luong = Long.parseLong(txtLuong.getText());
            CauThu cauThu = new CauThu(tuoi, hoTen, bangCap, luong);
            tmCT.addRow(cauThu.toObject());
            listCauThu.add(cauThu);
        } catch (TrongException e) {
            JOptionPane.showMessageDialog(this, "Khong de trong! ");
            return;
        } catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Nhap vao so! ");
            return;
        }
    }//GEN-LAST:event_btThemCTActionPerformed

    private void btLuuCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuCTActionPerformed
        // TODO add your handling code here:
        IOFile.viet(fCT, listCauThu);
    }//GEN-LAST:event_btLuuCTActionPerformed

    private void btThemViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemViTriActionPerformed
        // TODO add your handling code here:
        int n = listViTri.size();
        if(n > 0)
        {
            ViTri.setSma(listViTri.get(n - 1).getMaViTri()+ 1);
        }
        txtMaViTri.setText(ViTri.getSma() + "");
        int maViTri;
        String tenViTri;
        long heSoThuong;
        try {
            tenViTri = txtTenViTri.getText();
            heSoThuong = Long.parseLong(txtHeSoThuong.getText());
            ViTri vt = new ViTri(tenViTri, heSoThuong);
            tmVT.addRow(vt.toObject());
            listViTri.add(vt);
        } catch (TrongException e) {
            JOptionPane.showMessageDialog(this, "Khong de trong! ");
            return;
        } catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Nhap vao so! ");
            return;
        }
    }//GEN-LAST:event_btThemViTriActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int r = jTable2.getSelectedRow();
        txtMaViTri.setText(tmVT.getValueAt(r, 0).toString());
        txtTenViTri.setText(tmVT.getValueAt(r, 1).toString());
        txtHeSoThuong.setText(tmVT.getValueAt(r, 2).toString());
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void btLuuViTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuViTriActionPerformed
        IOFile.viet(fVT, listViTri);
    }//GEN-LAST:event_btLuuViTriActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void txtMaNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNV1ActionPerformed

    private void txtDiaChi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChi1ActionPerformed

    private void btThemNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemNV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btThemNV1ActionPerformed

    private void btSuaNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaNV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSuaNV1ActionPerformed

    private void btLuuNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuNV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLuuNV1ActionPerformed

    private void btLamMoiNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamMoiNV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLamMoiNV1ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable1.getSelectedRow();
        txtMaCT.setText(tmCT.getValueAt(r, 0).toString());
        txtTenCT.setText(tmCT.getValueAt(r, 1).toString());
        txtTuoi.setText(tmCT.getValueAt(r, 2).toString());
        cbBangCap.setSelectedItem(tmCT.getValueAt(r, 3).toString());
        txtLuong.setText(tmCT.getValueAt(r, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLamMoiNV1;
    private javax.swing.JButton btLuuCT;
    private javax.swing.JButton btLuuNV1;
    private javax.swing.JButton btLuuViTri;
    private javax.swing.JButton btSuaCT;
    private javax.swing.JButton btSuaNV1;
    private javax.swing.JButton btThemCT;
    private javax.swing.JButton btThemNV1;
    private javax.swing.JButton btThemViTri;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbBangCap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel panelDichVu;
    private javax.swing.JPanel panelNhanVien;
    private javax.swing.JPanel panelQuanLy;
    private javax.swing.JTextField txtDiaChi1;
    private javax.swing.JTextField txtHeSoThuong;
    private javax.swing.JTextField txtHoTenNV1;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMaCT;
    private javax.swing.JTextField txtMaNV1;
    private javax.swing.JTextField txtMaViTri;
    private javax.swing.JTextField txtTenCT;
    private javax.swing.JTextField txtTenViTri;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}

