/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.IOFile;
import controller.SoException;
import controller.TrongException;
import java.util.*;
import javax.swing.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import model.MatHang;

/**
 *
 * @author ADMIN
 */
public class FormKhachHang extends javax.swing.JPanel {

    DefaultTableModel d;
    private boolean them, sua;
    List <KhachHang> list = new ArrayList<>();
    String file = "src/controller/KH.dat";
    
    public FormKhachHang() {
        initComponents();
        String [] cols = {"Ma khach", "Ho ten", "Dia chi", "So dien thoai"};
        d = new DefaultTableModel(cols, 0);
        jTable1.setModel(d);
        buttonTrue();
        loadData();
        them = false;
        sua = false;
    }
    
    public void buttonTrue()
    {
        btThem.setEnabled(true);
        btXoa.setEnabled(true);
        btCapNhat.setEnabled(false);
        btBoQua.setEnabled(false);
    }
    
    public void buttonFalse()
    {
        btThem.setEnabled(false);
        btXoa.setEnabled(false);
        btCapNhat.setEnabled(true);
        btBoQua.setEnabled(true);
    }
    
    public void loadData()
    {
        File f = new File(file);
        if(f.exists())
            list = IOFile.doc(file);
        else
            IOFile.viet(file, list);
        d.setRowCount(0);
        for(KhachHang i : list)
        {
            d.addRow(i.toObjects());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();
        btGhi = new javax.swing.JButton();
        btDoc = new javax.swing.JButton();
        btBoQua = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ma khach: ");

        jLabel2.setText("Ten khach: ");

        jLabel3.setText("Dia chi: ");

        jLabel4.setText("So dien thoai: ");

        jTextField1.setEditable(false);
        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1)
                    .addComponent(jTextField4))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        btThem.setText("Them");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setText("Sua");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setText("Xoa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btCapNhat.setText("Cap nhat");
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });

        btGhi.setText("Ghi file");
        btGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGhiActionPerformed(evt);
            }
        });

        btDoc.setText("Doc file");
        btDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocActionPerformed(evt);
            }
        });

        btBoQua.setText("Bo qua");
        btBoQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBoQuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btThem)
                        .addGap(38, 38, 38)
                        .addComponent(btXoa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btSua)
                        .addGap(38, 38, 38)
                        .addComponent(btCapNhat)))
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btGhi)
                        .addGap(92, 92, 92)
                        .addComponent(btBoQua))
                    .addComponent(btDoc))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btXoa)
                    .addComponent(btGhi)
                    .addComponent(btBoQua))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSua)
                    .addComponent(btCapNhat)
                    .addComponent(btDoc))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        them = true;
        buttonFalse();
        if(list.size() > 0)
        {
            KhachHang.setIds(list.get(list.size() - 1).getId() + 1);
        }
        jTextField1.setText(KhachHang.getIds() + "");
        jTextField2.requestFocus();
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        int dong = jTable1.getSelectedRow();
        if(dong < 0 || dong > jTable1.getRowCount() - 1)
        {
            JOptionPane.showMessageDialog(this, "Chon dong trong bang!");
        }
        else
        {
            sua = true;
            buttonFalse();
            jTextField2.requestFocus();
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        int dong = jTable1.getSelectedRow();
        if(dong < 0 || dong > jTable1.getRowCount() - 1)
        {
            JOptionPane.showMessageDialog(this, "Chon dong trong bang!");
        }
        else
        {
            d.removeRow(dong);
            list.remove(dong);
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGhiActionPerformed
        IOFile.viet(file, list);
    }//GEN-LAST:event_btGhiActionPerformed

    private void btDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocActionPerformed
        list = IOFile.doc(file);
        d.setRowCount(0);
        for(KhachHang i : list)
        {
            d.addRow(i.toObjects());
        }
    }//GEN-LAST:event_btDocActionPerformed

    private void btBoQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBoQuaActionPerformed
       buttonTrue();
       them = false;
       sua = false;
       
    }//GEN-LAST:event_btBoQuaActionPerformed

    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
        if(them)
        {
            try {
                them = false;
                int id = Integer.parseInt(jTextField1.getText());
                String ten = jTextField2.getText();
                String diaChi = jTextField3.getText();
                String sdt = jTextField4.getText();
                if(ten.isEmpty() || diaChi.isEmpty() || sdt.isEmpty())
                    throw new TrongException();
                if(!sdt.matches("^\\d+"))
                    throw new SoException();
                KhachHang temp = new KhachHang(id, ten, diaChi, sdt);
                list.add(temp);
                d.addRow(temp.toObjects());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Nhap vao so!");
                jTextField3.requestFocus();
            } catch (TrongException ex) {
                JOptionPane.showMessageDialog(this, "Khong de trong!");
                jTextField2.requestFocus();
            } catch (SoException ex) {
                JOptionPane.showMessageDialog(this, "Nhap vao so!");
            }
        }
        if(sua)
        {
            sua = false;
            int row = jTable1.getSelectedRow();
            try {
                them = false;
                int id = Integer.parseInt(jTextField1.getText());
                String ten = jTextField2.getText();
                String diaChi = jTextField3.getText();
                String sdt = jTextField4.getText();
                if(ten.isEmpty() || diaChi.isEmpty() || sdt.isEmpty())
                    throw new TrongException();
                if(!sdt.matches("^\\d+"))
                    throw new SoException();
                KhachHang temp = new KhachHang(id, ten, diaChi, sdt);
                list.set(row, temp);
                d.setValueAt(id, row, 0);
                d.setValueAt(ten, row, 1);
                d.setValueAt(diaChi, row, 2);
                d.setValueAt(sdt, row, 3);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Nhap vao so!");
                jTextField3.requestFocus();
            } catch (TrongException ex) {
                JOptionPane.showMessageDialog(this, "Khong de trong!");
                jTextField2.requestFocus();
            } catch (SoException ex) {
                JOptionPane.showMessageDialog(this, "Nhap vao so!");
            }
        }
        buttonTrue();
    }//GEN-LAST:event_btCapNhatActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int dong = jTable1.getSelectedRow();
        jTextField1.setText(d.getValueAt(dong, 0).toString());
        jTextField2.setText(d.getValueAt(dong, 1).toString());
        jTextField3.setText(d.getValueAt(dong, 2).toString());
        jTextField4.setText(d.getValueAt(dong, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBoQua;
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btDoc;
    private javax.swing.JButton btGhi;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
