/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.IOFile;
import controller.SdtException;
import controller.TrongException;
import java.util.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import model.MatHang;
import model.NhanVien;
import model.QLBH;

/**
 *
 * @author ADMIN
 */
public class FormQLBH extends javax.swing.JPanel {
    
    DefaultTableModel d;
    private boolean them, sua;
    String file = "src/controller/QLBH.dat";
    String file1 = "src/controller/MH.dat";
    String file2 = "src/controller/NV.dat";
    List<QLBH> list = new ArrayList();
    List<MatHang> list1 = new ArrayList<>();
    List<NhanVien> list2 = new ArrayList();

    /**
     * Creates new form FormMatHang
     */
    public FormQLBH() {
        try {
            this.list1 = IOFile.doc(file1);
            this.list2 = IOFile.doc(file2);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormQLBH.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        String [] cols = {"Ma nhan vien", "Ho ten", "Ma mat hang", 
            "Ten mat hang", "Nhom hang"};
        d = new DefaultTableModel(cols, 0);
        jTable1.setModel(d);
        loadData();
        loadMa();
        buttonState(true);
        them = false;
        sua = false;
        
    }

    private void buttonState(boolean b)
    {
        btThem.setEnabled(b);
        btSua.setEnabled(b);
        btCapNhat.setEnabled(!b);
        btBoQua.setEnabled(!b);
    }
    
    private void loadMa()
    {
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        try {
            list1 = IOFile.doc(file1);
            list2 = IOFile.doc(file2);
            for(MatHang i : list1)
            {
                jComboBox1.addItem(i.getId() + "");
            }
            for(NhanVien i : list2)
            {
                jComboBox2.addItem(i.getId() + "");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormQLBH.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    
    private boolean ktTrung(int ma1, int ma2)
    {
        for(QLBH i : list)
        {
            if(i.getM().getId() == ma1 && i.getN().getId() == ma2)
                return false;
        }
        return true;
    }
    
    private boolean ktMax(int ma)
    {
        int count = 0;
        for(QLBH i : list)
        {
            if(i.getN().getId() == ma)
                count++;
        }
        return count < 6;
    }
    private void loadData()
    {
        try {
            list1 = IOFile.doc(file1);
            list2 = IOFile.doc(file2);
            File f = new File(file);
            if(f.exists())
                list = IOFile.doc(file);
            else
                IOFile.viet(file, list);
            d.setRowCount(0);
            for(QLBH i : list)
            {
                d.addRow(i.toObjects());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormQLBH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private MatHang getMatHang(int ma)
    {
        try {
            list1 = IOFile.doc(file1);
            list2 = IOFile.doc(file2);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormQLBH.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        for(MatHang i : list1)
        {
            if(i.getId() == ma)
                return i;
        }
        return null;
    }
    
    private NhanVien getNhanVien(int ma)
    {
        
        for(NhanVien i : list2)
        {
            if(i.getId() == ma)
                return i;
        }
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();
        btBoQua = new javax.swing.JButton();
        btDoc = new javax.swing.JButton();
        btGhi = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ma mat hang: ");

        jLabel2.setText("Ma nhan vien: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Lam moi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sap xep theo ten nhan vien", "Sap xep theo nhom mat hang" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, 0, 201, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addGap(62, 62, 62)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btThem.setText("Them");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setText("Sua");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setText("Xoa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btCapNhat.setText("Cap nhat");
        btCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapNhatActionPerformed(evt);
            }
        });

        btBoQua.setText("Bo qua");
        btBoQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBoQuaActionPerformed(evt);
            }
        });

        btDoc.setText("Doc file");
        btDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocActionPerformed(evt);
            }
        });

        btGhi.setText("Ghi file");
        btGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGhiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btThem)
                    .addComponent(btSua))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btXoa)
                    .addComponent(btCapNhat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDoc)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btBoQua)
                        .addGap(70, 70, 70)
                        .addComponent(btGhi)))
                .addGap(191, 191, 191))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btBoQua)
                    .addComponent(btXoa)
                    .addComponent(btGhi))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCapNhat)
                    .addComponent(btSua)
                    .addComponent(btDoc))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        them = true;
        if(sua)
            sua = false;
        buttonState(false);
        jComboBox1.requestFocus();
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        int row = jTable1.getSelectedRow();
        if(row < 0 || row > jTable1.getRowCount() - 1)
        {
            JOptionPane.showMessageDialog(this, "Chon dong trong bang!");
            buttonState(true);
        }
        else
        {
            buttonState(false);
            sua = true;
            if(them)
                them = false;
            jComboBox1.requestFocus();
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        int row = jTable1.getSelectedRow();
        if(row < 0 || row > jTable1.getRowCount() - 1)
        {
            JOptionPane.showMessageDialog(this, "Chon dong trong bang!");
        }
        else
        {
            d.removeRow(row);
            list.remove(row);
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btBoQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBoQuaActionPerformed
        them = false;
        sua = false;
        buttonState(true);
    }//GEN-LAST:event_btBoQuaActionPerformed

    private void btGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGhiActionPerformed
        try {
            IOFile.viet(file, list);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormQLBH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btGhiActionPerformed

    private void btDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocActionPerformed
        try {
            list1 = IOFile.doc(file1);
            list2 = IOFile.doc(file2);
            list = IOFile.doc(file);
             d.setRowCount(0);
            for(QLBH i : list)
            {
                d.addRow(i.toObjects());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormQLBH.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btDocActionPerformed

    private void btCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapNhatActionPerformed
        int maMatHang = Integer.parseInt(jComboBox1.getSelectedItem().toString());
        int maNhanVien = Integer.parseInt(jComboBox2.getSelectedItem().toString());
        if(them)
        {
            them = false;
            if(ktMax(maNhanVien))
            {
                if(ktTrung(maMatHang, maNhanVien))
                {
                    QLBH temp = new QLBH(getMatHang(maMatHang), 
                            getNhanVien(maNhanVien));
                    list.add(temp);
                    d.addRow(temp.toObjects());
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Mat hang va nhan vien"
                            + " da ton tai!");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Qua so luong hang nhan vien"
                        + " co the ban!");
            }
        }
        if(sua)
        {
            sua = false;
            int row = jTable1.getSelectedRow();
            if(ktMax(maNhanVien))
            {
                if(ktTrung(maMatHang, maNhanVien))
                {
                    QLBH temp = new QLBH(getMatHang(maMatHang), 
                            getNhanVien(maNhanVien));
                    list.set(row, temp);
                    d.setValueAt(getNhanVien(maNhanVien).getId(), row, 0);
                    d.setValueAt(getNhanVien(maNhanVien).getTen(), row, 1);
                    d.setValueAt(getMatHang(maMatHang).getId(), row, 2);
                    d.setValueAt(getMatHang(maMatHang).getTen(), row, 3);
                    d.setValueAt(getMatHang(maMatHang).getNhom(), row, 4);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Mat hang va nhan vien"
                            + " da ton tai!");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Qua so luong hang nhan vien"
                        + " co the ban!");
            }
        }
        buttonState(true);
    }//GEN-LAST:event_btCapNhatActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        jComboBox1.setSelectedItem(d.getValueAt(row, 2));
        jComboBox2.setSelectedItem(d.getValueAt(row, 0));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       loadMa();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        if(jComboBox3.getSelectedIndex() == 0)
        {
            list.sort(new Comparator<QLBH>(){
                @Override
                public int compare(QLBH o1, QLBH o2) {
                    String t1 = o1.getN().getTen();
                    String t2 = o2.getN().getTen();
                    String name1 = t1.substring(t1.lastIndexOf(" ") + 1) + 1;
                    String name2 = t2.substring(t2.lastIndexOf(" ") + 1) + 1;
                    return name1.compareToIgnoreCase(name2);
                }
                
            });
            d.setRowCount(0);
            for(QLBH i : list)
                d.addRow(i.toObjects());
        }
        else
        {
            list.sort(new Comparator<QLBH>(){
                @Override
                public int compare(QLBH o1, QLBH o2) {
                    String t1 = o1.getM().getNhom();
                    String t2 = o2.getM().getNhom();
                    String name1 = t1.substring(t1.lastIndexOf(" ") + 1) + 1;
                    String name2 = t2.substring(t2.lastIndexOf(" ") + 1) + 1;
                    return name1.compareToIgnoreCase(name2);
                }
                
            });
            d.setRowCount(0);
            for(QLBH i : list)
                d.addRow(i.toObjects());
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBoQua;
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btDoc;
    private javax.swing.JButton btGhi;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
